### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by YuroKashine** [AIOMEGA/LethalPlus#3]
Hey mate,

Me again haha.
I have a question, i want to make a mod called lethaltactics which is focussed around adding special buyable and maybe findable items like a stab vest reducing incoming melee damage, a press vest reducing bullet damage, backpack giving 2 extra slots... etc and maybe some enemies and or enemy items like tripwire for example. I reckon youre also new to modding from ur last answer. I want to ask if u would be interested in working together and helping each other? I havent modded yet so this will be my first ever mod however i do have a background into the basics kf C#, php, html and now python.

I would love to hear from u!

**Comment by AIOMEGA** [comment]
Hi

I appreciate the offer but even my own mod is like at the bottom of my priorities currently. I'm a full time college student with a job so I don't have a whole lot of free time plus I don't exactly know how to add new items or monsters yet which is why I said in the other post that I was on break waiting for a certain person to finish making a tutorial on how to do so. How ever I can give you some resources on how to get started making a mod.
Here is a link to an official modding discord for Lethal Company: https://discord.gg/xdW888dD
Here is a step by step tutorial on how to get a very basic mod working on Lethal Comany: https://www.youtube.com/watch?v=4Q7Zp5K2ywI
and here is a wiki for making a mod I'd recommend reading through all of it: https://lethal.wiki/dev/overview

I'd recommend starting small with a simple feature to add, thats why I did the spray paint thing with my mod was because I just wanted to do something small and simple before diving into adding unique features.
